conn: Add conntrack dump while zeroing all counters
ti-mo/conntrack pull request #25
Opened 2021-04-21 09:31 UTC by linosgian

Apart from `IPCTNL_MSG_CT_GET` there's also `IPCTNL_MSG_CT_GET_CTRZERO`
which zeroes all the accounting counters that netfilter maintains. This
includes bytes and packets for each flow.

In order to avoid breaking the pre-existing [Dump](https://github.com/ti-mo/conntrack/blob/39fd2b98b91c2db9536dd524a88c1ee6af133838/conn.go#L131) function, I've opted to create a separate one, just for my usecase. 

If there's anything I missed, I'd be happy to fix it.

2021-05-17 11:17 UTC, linosgian commented
Hey @ti-mo, just bumping this one :smile:

2021-05-19 20:22 UTC, ti-mo commented
Hey @linosgian, thanks for the patch! Sorry for the long wait.

Since this is just a variation on the MessageType, we should probably consider passing a pointer to an options struct to the `Dump*()` family of functions. Something like the following:

```
type DumpOptions struct {
  ZeroCounters bool
}

func Dump(opts *DumpOptions) ... { ... }
```

For upgrading, minimal code changes would be required (`Dump(nil)` instead of `Dump()`), so it's not a big deal as long as the default behaviour stays the same.

Is this something you could tackle?

Thanks!

2021-06-04 22:24 UTC, linosgian commented
Hey @ti-mo I've pushed a couple of fixups to reflect what you're suggesting above.

Let me know if there's anything left

2021-06-07 15:04 UTC, ti-mo requested changes
Thank you, this looks excellent! Left a few remaining bits to take care of.

Please squash everything into a single commit, add a nice commit message and this is good to go! :rocket:

2021-06-07 15:04 UTC, ti-mo commented on conn.go
```suggestion
// DumpOptions is passed as an option to `Dump`-related methods to modify their behaviour.
```

2021-06-07 15:04 UTC, ti-mo commented on conn.go
> +	ZeroCounters bool
```suggestion
	// ZeroCounters resets all flows' counters to zero after the dump operation.
	ZeroCounters bool
```

2021-06-07 15:04 UTC, ti-mo commented on flow_integration_test.go
> +	require.NoError(t, err, "creating flow")
```suggestion
	require.NoError(t, c.Create(f), "creating flow")
```

2021-06-10 13:46 UTC, linosgian commented on flow_integration_test.go
> +	require.NoError(t, err, "creating flow")
Yep that was pointless :sweat_smile:

2021-06-10 13:46 UTC, linosgian commented
I've squashed everything. We should be good now :)

2021-06-10 14:24 UTC, ti-mo approved these changes
Thank you!

2021-06-10 14:24 UTC, merged